# Generated by Django 4.2.5 on 2023-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routinetimeslot',
            old_name='class_time',
            new_name='routine_time_slot',
        ),
    ]
