# Generated by Django 4.2.5 on 2023-10-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_department_alter_teacher_department_and_more'),
        ('academic', '0002_rename_class_time_routinetimeslot_routine_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='time_slot',
        ),
        migrations.CreateModel(
            name='ClassRoutine2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.routinetimeslot')),
                ('which_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
            ],
        ),
    ]
