# Generated by Django 4.2.5 on 2023-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutineTimeSlot',
            new_name='ClassRoutineTimeSlot',
        ),
        migrations.AlterField(
            model_name='classroutine2',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=255),
        ),
    ]
