# Generated by Django 4.2.5 on 2023-10-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_department_alter_teacher_department_and_more'),
        ('academic', '0004_rename_routinetimeslot_classroutinetimeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.DeleteModel(
            name='ClassRoutine',
        ),
    ]
