# Generated by Django 4.2.5 on 2023-10-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_subject_subject_teacher_delete_classroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamType',
        ),
        migrations.RemoveField(
            model_name='classroutine2',
            name='teacher',
        ),
    ]
