# Generated by Django 4.2.5 on 2023-10-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_classroutine2_day_viewclassroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewClassRoutine',
        ),
    ]
