# Generated by Django 4.2.5 on 2023-10-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_delete_viewclassroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=255)),
                ('first_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_class', to='academic.classroutine2')),
                ('second_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_class', to='academic.classroutine2')),
                ('third_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_class', to='academic.classroutine2')),
                ('which_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
            ],
        ),
    ]
