# Generated by Django 4.2.5 on 2023-10-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_viewclassroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewClassRoutine',
        ),
    ]
