# Generated by Django 4.2.5 on 2023-10-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroutine',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='fifth_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='first_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='fourth_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='second_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='sixth_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='third_class',
        ),
        migrations.RemoveField(
            model_name='classroutine',
            name='which_class',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='which_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='which_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassRoutine',
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='RoutineTimeSlot',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
