# Generated by Django 4.2.5 on 2023-09-17 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='fifth_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_class', to='student.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='first_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_class', to='student.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='fourth_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_class', to='student.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='second_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_class', to='student.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='sixth_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth_class', to='student.subject'),
        ),
        migrations.AddField(
            model_name='routine',
            name='third_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_class', to='student.subject'),
        ),
    ]
