# Generated by Django 4.2.5 on 2023-09-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachersdepartment_teacher_department'),
        ('student', '0006_routine_fifth_class_routine_first_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
