# Generated by Django 4.2.5 on 2023-09-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_routinetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_class', to='student.subject')),
            ],
        ),
        migrations.RenameModel(
            old_name='RoutineTime',
            new_name='RoutineTimeSlot',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AddField(
            model_name='classroutine',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.routinetimeslot'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='which_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroutine',
            unique_together={('which_class', 'day')},
        ),
    ]
