# Generated by Django 4.2.5 on 2023-09-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_classroutine_rename_routinetime_routinetimeslot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroutine',
            unique_together=set(),
        ),
    ]
