# Generated by Django 4.2.5 on 2023-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_classroutine_unique_together_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(),
        ),
    ]
